services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    depends_on:
      - db
      - cache
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: example
  cache:
    build: 
      context: .
      dockerfile: Dockerfile.cache

